server:
  port: 5000


telegram:
  botToken: "5175383932:AAFkBSFTUQSU4o1o9Q4nIspzgOTMhJqIG1k"
  botName: "Mon_Bon_Bot"
  webhookPath: "https://sogresh-bot.herokuapp.com/"
  api-request: "https://api.telegram.org/bot"
  chat:
    id: "-1001688280930"

java:
  runtime:
    version: 11