server:
  port: 5000


telegram:
  botToken: "5278510472:AAGfDAPhkInDdKUra0e4CkpV2hnK40R_4Kk"
  botName: "sogr_bot"
  webhookPath: "https://935c-188-32-209-237.ngrok.io"
  api-request: "https://api.telegram.org/bot"
  chat:
    id: "-1001502272659"