server:
  port: 5000


telegram:
  botToken: "5278510472:AAGfDAPhkInDdKUra0e4CkpV2hnK40R_4Kk"
  botName: "sogr_bot"
  webhookPath: "https://sogresh-bot.herokuapp.com/"
  api-request: "https://api.telegram.org/bot"
  chat:
    id: "-1001502272659"

java:
  runtime:
    version: 11